#!/usr/bin/env node

if (process.argv.length < 3) {
  console.error("missing comment character argument");
  process.exit();
}

const commentChar = process.argv[2];
var itr = 1;

process.stdin.setEncoding("utf8");
process.stdin.on("data", (chunk) => {
  chunk.split('\n').forEach((line) => {
    if (!line.startsWith("#!")) line += ` ${commentChar} line ${itr}`;
    console.log(line);
    itr++;
  });
});
